### PR TITLE
Just a lil cleanup, don't merge if it doesn't work

### PR DESCRIPTION
**Pull request by flfy**

### CODE REVIEW

**Comment by tilda** [comment]
Not sure if `let` if the best use for this.

**Review by tilda — COMMENTED** [review]
Not sure if `let` is the best thing for this.

`const` might work also. will do a bit of research of this

**Review by tilda — APPROVED** [review]
`let` has no real difference to `const` so I'll merge and test.

**Comment by tilda** [comment]
Seems to work so this change will stay

**Comment by tilda** [comment]
Update: `let` shouldn't really be used all the time but if it works, well I don't care.

**Comment by flfy** [comment]
Let is block scoped, say I have a loop that console logs a number 0-5. `var` would print `5`, `let` would print `1, 2, 3, 4, 5`. (I think, haha)

**Pull request merged**
